### ISSUE TITLE
Windows 10 gui 0.0.4

### ISSUE THREAD

**Issue by MadDogMayCry0** [silicoin-network/silicoin-blockchain#10]
What do i see after i start wallet. For a while :)
![Безымянный](https://user-images.githubusercontent.com/2493591/123790006-7f9ceb00-d8e6-11eb-848e-161eb9e6776a.png)

**Comment by albertxuzeng** [comment]
Can you provide the following files:

~/.silicoin/config/config.yaml
~/.silicoin/log/debug.log

**Comment by MadDogMayCry0** [comment]
> 
> 
> Can you provide the following files:
> 
> ~/.silicoin/config/config.yaml
> ~/.silicoin/log/debug.log

2021-06-29T09:37:18.413 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T09:37:18.426 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T09:37:22.421 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T09:37:22.442 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T09:37:26.432 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T09:37:26.453 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T09:37:30.434 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T09:37:30.461 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T09:37:34.440 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T09:37:34.475 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T09:42:23.827 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T09:42:23.834 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T09:42:27.839 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T09:42:27.842 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T09:50:51.544 wallet chia.rpc.wallet_rpc_api    : ERROR    error No backup on backup service
2021-06-29T09:50:51.764 wallet chia.rpc.wallet_rpc_api    : ERROR    error No backup on backup service
2021-06-29T10:52:25.900 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:25.904 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:25.908 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:25.910 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:29.910 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:29.912 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:29.922 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:29.914 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:33.927 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:33.930 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:34.920 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:33.927 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:37.935 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:37.940 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:38.929 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:38.936 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:41.957 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:41.962 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:42.928 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:42.952 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:45.959 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:45.974 harvester chia.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:46.935 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T10:52:46.970 wallet chia.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56400
2021-06-29T11:07:42.073 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 604, in _sync
  File "chia\wallet\wallet_node.py", line 643, in fetch_blocks_and_validate
ValueError: Peer returned no response

2021-06-29T11:07:42.198 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Peer returned no response Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 604, in _sync
  File "chia\wallet\wallet_node.py", line 643, in fetch_blocks_and_validate
ValueError: Peer returned no response

2021-06-29T11:07:42.198 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 5184-5216. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 515, in sync_job
  File "chia\wallet\wallet_node.py", line 614, in _sync
RuntimeError: Was not able to add blocks 5184-5216

**Comment by eks500** [comment]
I'm seeing this same situation, putting the log level to INFO writes thousands of:

`2021-06-30T08:58:57.047 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 9447}
2021-06-30T08:58:57.051 harvester harvester_server        : INFO     Cannot connect to host 127.0.0.1:9447 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')]
2021-06-30T08:58:59.842 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 9444}
2021-06-30T08:58:59.842 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:9444 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')]
2021-06-30T08:59:00.060 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 9447}
2021-06-30T08:59:00.061 harvester harvester_server        : INFO     Cannot connect to host 127.0.0.1:9447 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')]
2021-06-30T08:59:02.858 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 9444}
2021-06-30T08:59:02.858 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:9444 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')]
2021-06-30T08:59:03.077 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 9447}
2021-06-30T08:59:03.077 harvester harvester_server        : INFO     Cannot connect to host 127.0.0.1:9447 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')]
2021-06-30T08:59:05.873 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 9444}
2021-06-30T08:59:05.873 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:9444 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')]
2021-06-30T08:59:06.091 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 9447}
2021-06-30T08:59:06.094 harvester harvester_server        : INFO     Cannot connect to host 127.0.0.1:9447 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')]
2021-06-30T08:59:08.879 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 9444}
2021-06-30T08:59:08.884 wallet wallet_server              : INFO     Cannot connect to host 127.0.0.1:9444 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')]
2021-06-30T08:59:09.123 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 9447}
2021-06-30T08:59:09.127 harvester harvester_server        : INFO     Cannot connect to host 127.0.0.1:9447 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')]
2021-06-30T08:59:11.888 wallet wallet                     : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 9444}`

**Comment by Yu53** [comment]
Try to use another pc where spare client is not running, this helped me out.

**Comment by Eskha93** [comment]
same error in 3 diff. PC

**Comment by albertxuzeng** [comment]
Silicoin may not run with other Chia fork project at the same machine. So please try to close other Chia fork project or use another machine to run Silicoin.

**Comment by eks500** [comment]
> Silicoin may not run with other Chia fork project at the same machine. So please try to close other Chia fork project or use another machine to run Silicoin.

That make it useless unfortunately, I have other 5 forks running without a problem apart from Chia itself.
