### ISSUE TITLE
[BUG]IT  NOT WORK 

### ISSUE THREAD

**Issue by Nok74** [silicoin-network/silicoin-blockchain#12]
* File "chia\util\type_checking.py", line 72, in parse_item
  File "chia\util\struct_stream.py", line 17, in __new__
ValueError: Value 1119447 of size 21 does not fit into uint16 of size 16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chia\util\type_checking.py", line 75, in parse_item
  File "chia\util\struct_stream.py", line 34, in from_bytes
TypeError: a bytes-like object is required, not 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kimti\Downloads\chia\chia-blockchain\venv\Lib\site-packages\chia\server\start_harvester.py", line 57, in <module>
  File "C:\Users\kimti\Downloads\chia\chia-blockchain\venv\Lib\site-packages\chia\server\start_harvester.py", line 52, in main
  File "C:\Users\kimti\Downloads\chia\chia-blockchain\venv\Lib\site-packages\chia\server\start_harvester.py", line 26, in service_kwargs_for_harvester
  File "<string>", line 5, in __init__
  File "chia\util\type_checking.py", line 93, in __post_init__
  File "chia\util\type_checking.py", line 77, in parse_item
  File "chia\util\struct_stream.py", line 36, in from_bytes
AssertionError
[19416] Failed to execute script start_harvester
Traceback (most recent call last):
  File "C:\Users\kimti\Downloads\chia\chia-blockchain\venv\Lib\site-packages\chia\server\start_farmer.py", line 68, in <module>
  File "C:\Users\kimti\Downloads\chia\chia-blockchain\venv\Lib\site-packages\chia\server\start_farmer.py", line 63, in main
  File "C:\Users\kimti\Downloads\chia\chia-blockchain\venv\Lib\site-packages\chia\server\start_farmer.py", line 38, in service_kwargs_for_farmer
  File "chia\farmer\farmer.py", line 79, in __init__
  File "chia\farmer\farmer.py", line 79, in <listcomp>
ValueError: non-hexadecimal number found in fromhex() arg at position 97
[6860] Failed to execute script start_farmer

**Comment by albertxuzeng** [comment]
Please provide the OS version, silicoin version and the following files:

~/.silicoin/config/config.yaml
~/.silicoin/log/debug.log
