### ISSUE TITLE
Wallet stopped syncing at 17772 (advances extremely slowly)

### ISSUE THREAD

**Issue by chnapo** [silicoin-network/silicoin-blockchain#125]
Log: 2021-11-09T18:05:03.092 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 17771-17803. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 641, in sync_job
  File "chia\wallet\wallet_node.py", line 701, in _sync
  File "chia\wallet\wallet_node.py", line 598, in batch_sync_to_peak
RuntimeError: Was not able to add blocks 17771-17803

2021-11-09T18:05:11.710 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Value error peer sent us invalid block Err.INVALID_REQUIRED_ITERS None Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 588, in batch_sync_to_peak
  File "chia\wallet\wallet_node.py", line 798, in fetch_blocks_and_validate
ValueError: Value error peer sent us invalid block Err.INVALID_REQUIRED_ITERS None

2021-11-09T18:05:11.711 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 17771-17803. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 641, in sync_job
  File "chia\wallet\wallet_node.py", line 701, in _sync
  File "chia\wallet\wallet_node.py", line 598, in batch_sync_to_peak
RuntimeError: Was not able to add blocks 17771-17803

2021-11-09T18:05:11.712 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None
2021-11-09T18:05:20.871 wallet chia.wallet.wallet_node    : ERROR    Error while trying to fetch from peer:Value error peer sent us invalid block Err.INVALID_REQUIRED_ITERS None Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 588, in batch_sync_to_peak
  File "chia\wallet\wallet_node.py", line 798, in fetch_blocks_and_validate
ValueError: Value error peer sent us invalid block Err.INVALID_REQUIRED_ITERS None

2021-11-09T18:05:20.872 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 17771-17803. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 641, in sync_job
  File "chia\wallet\wallet_node.py", line 701, in _sync
  File "chia\wallet\wallet_node.py", line 598, in batch_sync_to_peak
RuntimeError: Was not able to add blocks 17771-17803

2021-11-09T18:05:20.874 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None

Wallet syncs extremely slowly or not at all.

**Comment by silahendaz** [comment]
Can I use my chia plots in silicoin program ?  I tryed but not won any SIT.  not farming with chia plots.

**Comment by chnapo** [comment]
Yes, chia plots work with sit, also you can farm chia at the same time

Dňa ut 9. 11. 2021, 18:32 silahendaz ***@***.***> napísal(a):

**Comment by dipol0** [comment]
Silicoin suxx ?

2021-11-10T00:40:50.214 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 17771-17803. Traceback (most recent call last):
  File "chia/wallet/wallet_node.py", line 641, in sync_job
  File "chia/wallet/wallet_node.py", line 701, in _sync
  File "chia/wallet/wallet_node.py", line 598, in batch_sync_to_peak
RuntimeError: Was not able to add blocks 17771-17803

2021-11-10T00:40:50.214 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None

**Comment by dipol0** [comment]
Try FIX - https://discord.com/channels/855895952757620757/864525972131545148/907713905877475329

**Comment by MycaelRaustin** [comment]
One possible reason is old peers.

Discord recommends that we increase the config's value tp:
target_peer_count: 10

If by chance, all the peers you scored there are dominating with the correct network height, then you're good.
If not, you could still get stuck in syncing.

For me, I'm running a small bash script to manage my connections
It works for my case, ensures that all old peers with diff ports are disconnected. Lol
Works for linux; for Windows, I'm running this within cygwin.

> #!/bin/sh
while true;
do echo "Checking Peers";
outsider=`./sit show -c|grep FULL|sed 's/  */,/g'|grep -v 22222|awk -F',' '{print $4}'|sed 's/\.*//g'`;
for node in $outsider; do ./sit show -r $node;echo terminated $node; done;
sleep 60
done;

**Comment by albertcoady** [comment]
Version 1.1.1 fix this problem, please update to the new version.
