### ISSUE TITLE
Unable to sync with 1.1.1 ##FIXED##

### ISSUE THREAD

**Issue by OldButtKicking** [silicoin-network/silicoin-blockchain#129]
**Describe the bug**
I get 22222 port connections I get Sync 0/XXXXX on screen 
Then I loose the connections over and over

communication in the log looks like this...
2021-11-10T20:20:07.893 full_node chia.full_node.full_node: INFO     Collected a total of 1 peaks.
2021-11-10T20:20:07.894 full_node chia.full_node.full_node: INFO     Selected peak 26457, e4b7bb3a38eb4abf18e83e272705f01e2030ca5dcfb6d344536325eaa99b0b9d
2021-11-10T20:20:08.111 full_node chia.full_node.full_node: INFO     Total of 1 peers with peak 26457
2021-11-10T20:20:08.111 full_node chia.full_node.full_node: INFO     Requesting weight proof from peer 182.19.171.153 up to height 26457

and then there is either nothing or something like the following

2021-11-10T20:20:25.516 full_node full_node_server        : INFO     Connection closed: 182.19.171.153, node id: ab41ca3857cd9c191eb183b76012f90c74dd8f38c05ba72494dd2376f764c8bd
2021-11-10T20:20:25.517 full_node full_node_server        : WARNING  Banning 182.19.171.153 for 600 seconds
2021-11-10T20:20:25.518 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '182.19.171.153', 'port': 22222}
2021-11-10T20:20:25.518 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'ValueError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 743, in _sync
ValueError: Weight proof validation failed

**Desktop**

- OS:Windows 
- OS Version/Flavor: 10
- CPU: intel i7-9700k cpu @3.60GHz

**Comment by albertcoady** [comment]
47.243.76.11:22222
82.157.30.197:22222
42.194.142.34:22222
18.135.187.74:22222
3.68.181.176:22222
18.179.135.79:22222
3.106.3.111:22222

Please try to connect the nodes above manually.

**Comment by OldButtKicking** [comment]
Same issue. I can connect to them but before the first block sync they are disconnected

2021-11-11T11:25:32.030 full_node chia.full_node.weight_proof: INFO     validate weight proof peak height 29503
2021-11-11T11:25:32.033 full_node chia.full_node.weight_proof: INFO     validating 76 sub epochs
2021-11-11T11:25:32.034 full_node chia.full_node.weight_proof: ERROR    failed to validate ses hashes block height 29212
2021-11-11T11:25:32.034 full_node chia.full_node.weight_proof: ERROR    weight proof failed sub epoch data validation
2021-11-11T11:25:32.037 full_node full_node_server        : INFO     Cannot connect to host 103.53.27.253:11444 ssl:<ssl.SSLContext object at 0x0000019E5E11E940> [The semaphore timeout period has expired]
2021-11-11T11:25:32.038 full_node full_node_server        : INFO     Cannot connect to host 45.129.202.137:11444 ssl:<ssl.SSLContext object at 0x0000019E5BC612C0> [The semaphore timeout period has expired]
2021-11-11T11:25:32.199 full_node full_node_server        : INFO     Connection closed: 47.243.76.11, node id: 02d79eb9f351c1aee47ecdca830a77fe1f338d023c0fc2b8edaa4f9cea966e78
2021-11-11T11:25:32.199 full_node full_node_server        : WARNING  Banning 47.243.76.11 for 600 seconds
2021-11-11T11:25:32.200 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '**47.243.76.11**', 'port': 22222}
2021-11-11T11:25:32.201 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'ValueError'>Traceback (most recent call last):
  File "chia\full_node\full_node.py", line 743, in _sync
ValueError: Weight proof validation failed

2021-11-11T11:25:32.201 full_node chia.full_node.full_node: INFO     long sync done
2021-11-11T11:25:32.364 farmer chia.farmer.farmer         : INFO     [debug] clear cache

**Comment by OldButtKicking** [comment]
I deleted everything and reinstalled and this time it is working. Thanks for the nodes albertcoady

**Comment by OldButtKicking** [comment]
I deleted the SIT folder C:\Users\xxx\AppData\Local\SIT and C:\Users\xxx\.sit folder and reinstalled now working.
