### ISSUE TITLE
recover 7/8 NFT block rewar with ubuntu

### ISSUE THREAD

**Issue by yhhwpp** [silicoin-network/silicoin-blockchain#147]
I only find the  way for window, but How to recover your 7/8 NFT block reward with ubuntu

**Comment by albertcoady** [comment]
Please refer the command help document: sit wallet recover_pool_nft -h

**Comment by yhhwpp** [comment]
have the rpc api?

**Comment by yhhwpp** [comment]
i run  `sit wallet recover_pool_nft --contract-hash *** --launcher-hash *** -f 2711591356`

throw the error
```

Traceback (most recent call last):
  File "chia/cmds/chia.py", line 135, in <module>
  File "chia/cmds/chia.py", line 131, in main
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "chia/cmds/wallet.py", line 265, in recover_pool_nft
  File "nest_asyncio.py", line 32, in run
  File "nest_asyncio.py", line 70, in run_until_complete
  File "asyncio/futures.py", line 178, in result
  File "asyncio/tasks.py", line 280, in __step
  File "chia/cmds/wallet.py", line 224, in do_recover_pool_nft
  File "chia/util/byte_types.py", line 11, in hexstr_to_bytes
ValueError: non-hexadecimal number found in fromhex() arg at position 0
[1559218] Failed to execute script chia

```

**Comment by albertcoady** [comment]
> i run `sit wallet recover_pool_nft --contract-hash *** --launcher-hash *** -f 2711591356`
> 
> throw the error
> 
> ```
> 
> Traceback (most recent call last):
>   File "chia/cmds/chia.py", line 135, in <module>
>   File "chia/cmds/chia.py", line 131, in main
>   File "click/core.py", line 829, in __call__
>   File "click/core.py", line 782, in main
>   File "click/core.py", line 1259, in invoke
>   File "click/core.py", line 1259, in invoke
>   File "click/core.py", line 1066, in invoke
>   File "click/core.py", line 610, in invoke
>   File "chia/cmds/wallet.py", line 265, in recover_pool_nft
>   File "nest_asyncio.py", line 32, in run
>   File "nest_asyncio.py", line 70, in run_until_complete
>   File "asyncio/futures.py", line 178, in result
>   File "asyncio/tasks.py", line 280, in __step
>   File "chia/cmds/wallet.py", line 224, in do_recover_pool_nft
>   File "chia/util/byte_types.py", line 11, in hexstr_to_bytes
> ValueError: non-hexadecimal number found in fromhex() arg at position 0
> [1559218] Failed to execute script chia
> ```

Can you show me your command? It is safe that no matter who execute this command the missing coin will go to your wallet finally.

**Comment by yhhwpp** [comment]
Have the rpc api to get the total coins that can recovered ?

**Comment by yhhwpp** [comment]
Have the rpc api to get the total coins that can recovered  and  total coins not recovered?

**Comment by albertcoady** [comment]
Yes, you can use "get_coin_records_by_puzzle_hash" api to get the total coins that can recovered.

**Comment by yhhwpp** [comment]
ok
