### ISSUE TITLE
ValueError: [ERROR] Error short batch syncing, could not fetch block at height 82560

### ISSUE THREAD

**Issue by maxchock** [silicoin-network/silicoin-blockchain#160]
There are few errors keep repeating: below is the log that I capture. `2021-11-23T14:58:34.295 full_node full_node_server        : WARNING  Banning 183.156.74.203 for 10 seconds
2021-11-23T14:58:47.033 full_node chia.full_node.weight_proof: ERROR    failed to validate ses hashes block height 134805
2021-11-23T14:58:47.034 full_node chia.full_node.weight_proof: ERROR    weight proof failed sub epoch data validation
2021-11-23T14:58:47.035 full_node full_node_server        : ERROR    Exception: Error short batch syncing, could not fetch block at height 82560, {'host': '178.121.23.114', 'port': 11444}. Traceback (most recent call last):
  File "chia/server/server.py", line 559, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 115, in new_peak
  File "chia/full_node/full_node.py", line 433, in new_peak
  File "chia/full_node/full_node.py", line 266, in short_sync_batch
ValueError: Error short batch syncing, could not fetch block at height 82560

2021-11-23T14:58:47.035 full_node full_node_server        : ERROR    Exception: Error short batch syncing, could not fetch block at height 82560 <class 'ValueError'>, closing connection {'host': '178.121.23.114', 'port': 11444}. Traceback (most recent call last):
  File "chia/server/server.py", line 569, in api_call
  File "asyncio/tasks.py", line 455, in wait_for
  File "chia/server/server.py", line 566, in wrapped_coroutine
  File "chia/server/server.py", line 559, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 115, in new_peak
  File "chia/full_node/full_node.py", line 433, in new_peak
  File "chia/full_node/full_node.py", line 266, in short_sync_batch
ValueError: Error short batch syncing, could not fetch block at height 82560

2021-11-23T14:58:47.035 full_node full_node_server        : ERROR    Exception: Error short batch syncing, could not fetch block at height 82560, {'host': '178.121.23.114', 'port': 11444}. Traceback (most recent call last):
  File "chia/server/server.py", line 559, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 115, in new_peak
  File "chia/full_node/full_node.py", line 433, in new_peak
  File "chia/full_node/full_node.py", line 266, in short_sync_batch
ValueError: Error short batch syncing, could not fetch block at height 82560

2021-11-23T14:58:47.036 full_node full_node_server        : ERROR    Exception: Error short batch syncing, could not fetch block at height 82560 <class 'ValueError'>, closing connection {'host': '178.121.23.114', 'port': 11444}. Traceback (most recent call last):
  File "chia/server/server.py", line 569, in api_call
  File "asyncio/tasks.py", line 455, in wait_for
  File "chia/server/server.py", line 566, in wrapped_coroutine
  File "chia/server/server.py", line 559, in wrapped_coroutine
  File "chia/full_node/full_node_api.py", line 115, in new_peak
  File "chia/full_node/full_node.py", line 433, in new_peak
  File "chia/full_node/full_node.py", line 266, in short_sync_batch
ValueError: Error short batch syncing, could not fetch block at height 82560

2021-11-23T14:58:47.039 full_node full_node_server        : WARNING  Banning 178.121.23.114 for 600 seconds
2021-11-23T14:58:47.040 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'ValueError'>Traceback (most recent call last):
  File "chia/full_node/full_node.py", line 743, in _sync
ValueError: Weight proof validation failed
`
the farmer looks running fine. I was still able to get reward yesterday afternoon. But no reward since, it is almost 24 hours in between. last Height farm was **79630**

**Comment by albertcoady** [comment]
What is your Silicoin version and how many plot files you are farming, how many SIT are you staking?

**Comment by maxchock** [comment]
> What is your Silicoin version and how many plot files you are farming, how many SIT are you staking?

i'm currently using 1.1.3, 1776 plots and 27SIT staking

**Comment by chiamb** [comment]
I have same problem...

**Comment by albertcoady** [comment]
> > What is your Silicoin version and how many plot files you are farming, how many SIT are you staking?
> 
> i'm currently using 1.1.3, 1776 plots and 27.1310 SIT staking

I think it is normal since your staking factor is around 4.9, which means your actual total size of plots is about 36 T.

**Comment by PrEzi3** [comment]
the Error can be IMHO ignored as with the restart also Port have been switched from 11444 to 22444. I also get some "old" clients trying to connect to me -- you can cut them out in your firewall or let the full node on your side ban them.

**Comment by maxchock** [comment]
So is it OK to ban 11444 on the router side?

**Comment by albertcoady** [comment]
> So is it OK to ban 11444 on the router side? 11444 will no longer be use?

Yes, 11444 will no longer be use.
