### ISSUE TITLE
[BUG]  No module named '_ssl'

### ISSUE THREAD

**Issue by JustAlias** [silicoin-network/silicoin-blockchain#176]
(venv) [root@localhost silicoin]# sit
Traceback (most recent call last):
  File "/root/silicoin/silicoin/venv/bin/sit", line 5, in <module>
    from chia.cmds.chia import main
  File "/root/silicoin/silicoin/venv/lib/python3.7/site-packages/chia/cmds/chia.py", line 9, in <module>
    from chia.cmds.init import init_cmd
  File "/root/silicoin/silicoin/venv/lib/python3.7/site-packages/chia/cmds/init.py", line 45, in <module>
    from chia.cmds.passphrase_funcs import remove_passphrase_options_from_cmd
  File "/root/silicoin/silicoin/venv/lib/python3.7/site-packages/chia/cmds/passphrase_funcs.py", line 4, in <module>
    from chia.daemon.client import acquire_connection_to_daemon
  File "/root/silicoin/silicoin/venv/lib/python3.7/site-packages/chia/daemon/client.py", line 3, in <module>
    import ssl
  File "/usr/local/python3/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

**Comment by albertcoady** [comment]
You can try cloning the source code from GitHub and run "sh install.sh" to install Silicoin
