### ISSUE TITLE
[BUG] version 1.2.0 has C:\Users\Infothinker-0702 directories hard coded

### ISSUE THREAD

**Issue by demusss** [silicoin-network/silicoin-blockchain#183]
I was having problems syncing so installed latest version 1.2.0 if windows setup

Syncing now works but no plots are shown in Farmer

In the log is this
===============================
2021-12-23T15:38:59.332 daemon __main__                   : ERROR    Error while handling message: Traceback (most recent call last):
  File "C:\Users\Infothinker-0702\work\silicoin2\venv\Lib\site-packages\chia\daemon\server.py", line 199, in safe_handle
  File "C:\Users\Infothinker-0702\work\silicoin2\venv\Lib\site-packages\chia\daemon\server.py", line 333, in handle_message
  File "C:\Users\Infothinker-0702\work\silicoin2\venv\Lib\site-packages\chia\daemon\server.py", line 572, in get_plotters
  File "chia\plotters\plotters.py", line 358, in get_available_plotters
  File "chia\plotters\chiapos.py", line 16, in get_chiapos_install_info
  File "pkg_resources\__init__.py", line 466, in get_distribution
  File "pkg_resources\__init__.py", line 342, in get_provider
  File "pkg_resources\__init__.py", line 886, in require
  File "pkg_resources\__init__.py", line 772, in resolve
pkg_resources.DistributionNotFound: The 'chiapos' distribution was not found and is required by the application
===============================

who is user Infothinker-0702 ?? Its not my userid

**Comment by minguohua** [comment]
me too,must clear all,NO uninstall！then install again.
