### ISSUE TITLE
[BUG] Syncing node error

### ISSUE THREAD

**Issue by Rakus73** [silicoin-network/silicoin-blockchain#189]
**Describe the bug**
Syncing node stopped in blocks 274698-274730. Not connecting another node.

**Screenshots**
2022-01-06T14:06:45.911 full_node chia.full_node.full_node: ERROR    Invalid block from peer: {'host': '95.78.232.45', 'port': 22222} Err.INVALID_TOTAL_ITERS
2022-01-06T14:06:45.911 full_node full_node_server        : ERROR    Exception: Error short batch syncing, failed to validate blocks 274695-274727, {'host': '95.78.232.45', 'port': 22222}. Traceback (most recent call last):
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 124, in new_peak
  File "chia\full_node\full_node.py", line 527, in new_peak
  File "chia\full_node\full_node.py", line 397, in short_sync_batch
  File "chia\full_node\full_node.py", line 367, in short_sync_batch
ValueError: Error short batch syncing, failed to validate blocks 274695-274727

2022-01-06T14:06:45.911 full_node full_node_server        : ERROR    Exception: Error short batch syncing, failed to validate blocks 274695-274727 <class 'ValueError'>, closing connection {'host': '95.78.232.45', 'port': 22222}. Traceback (most recent call last):
  File "chia\server\server.py", line 576, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 573, in wrapped_coroutine
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 124, in new_peak
  File "chia\full_node\full_node.py", line 527, in new_peak
  File "chia\full_node\full_node.py", line 397, in short_sync_batch
  File "chia\full_node\full_node.py", line 367, in short_sync_batch
ValueError: Error short batch syncing, failed to validate blocks 274695-274727

2022-01-06T14:06:46.239 full_node full_node_server        : WARNING  Banning 95.78.232.45 for 10 seconds
2022-01-06T14:06:51.028 full_node chia.full_node.full_node: ERROR    Invalid block from peer: {'host': '187.106.245.66', 'port': 22222} Err.INVALID_TOTAL_ITERS
2022-01-06T14:06:51.028 full_node full_node_server        : ERROR    Exception: Error short batch syncing, failed to validate blocks 274698-274730, {'host': '187.106.245.66', 'port': 22222}. Traceback (most recent call last):
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 124, in new_peak
  File "chia\full_node\full_node.py", line 527, in new_peak
  File "chia\full_node\full_node.py", line 397, in short_sync_batch
  File "chia\full_node\full_node.py", line 367, in short_sync_batch
ValueError: Error short batch syncing, failed to validate blocks 274698-274730

**Desktop**
- OS: Win10
- CPU: AMD Ryzen 7 3800X 8-Core Processor 3.90 GHz RAM: 64GB

**Comment by albertcoady** [comment]
Had you tried restarting the app?

**Comment by Rakus73** [comment]
Yes, I had sttopped and It connect with same IP blocked in 274698. I deleted IP and It try to connect another IP but it not kept them connected.
Now, I am starting to reload db node again. I'm trying to connect IP with a Peak Height over 274698.
Thanks

**Comment by albertcoady** [comment]
You can download the most latest db from our discord channel. It may save you a lot of time.

**Comment by Rakus73** [comment]
ok. Let's go!
