### ISSUE TITLE
Error short batch syncing: unable to sync

### ISSUE THREAD

**Issue by ariegrossman** [silicoin-network/silicoin-blockchain#209]
2022-02-15T11:50:52.048 full_node full_node_server        : ERROR    Exception: Error short batch syncing, failed to validate blocks 413325-413357 <class 'ValueError'>, closing connection {'host': '195.36.10.19', 'port': 22222}. Traceback (most recent call last):
  File "/home/arie/Chia/silicoin-blockchain/chia/server/server.py", line 576, in api_call
    response: Optional[Message] = await asyncio.wait_for(wrapped_coroutine(), timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/arie/Chia/silicoin-blockchain/chia/server/server.py", line 573, in wrapped_coroutine
    raise e
  File "/home/arie/Chia/silicoin-blockchain/chia/server/server.py", line 566, in wrapped_coroutine
    result = await coroutine
  File "/home/arie/Chia/silicoin-blockchain/chia/full_node/full_node_api.py", line 124, in new_peak
    return await self.full_node.new_peak(request, peer)
  File "/home/arie/Chia/silicoin-blockchain/chia/full_node/full_node.py", line 527, in new_peak
    if await self.short_sync_batch(peer, uint32(max(curr_peak_height - 128, 0)), request.height):
  File "/home/arie/Chia/silicoin-blockchain/chia/full_node/full_node.py", line 397, in short_sync_batch
    raise e
  File "/home/arie/Chia/silicoin-blockchain/chia/full_node/full_node.py", line 367, in short_sync_batch
    raise ValueError(
ValueError: Error short batch syncing, failed to validate blocks 413325-413357

**Comment by albertcoady** [comment]
Can your node sync to the latest height?

**Comment by ariegrossman** [comment]
No. I have two nodes. Both are stuck at block 413325. This can't be just me.

**Comment by albertcoady** [comment]
You can use the most updated db snapshot to restore the node and catch up with the latest height.
