### ISSUE TITLE
[BUG] recover_pool_nft throws exception

### ISSUE THREAD

**Issue by FlexiMiners** [silicoin-network/silicoin-blockchain#211]
When trying to run the ntf recover process form the linux command line, it correctly identifies the coins, but throws an exception
**To Reproduce**

1. sit wallet recover_pool_nft --launcher-hash xxxxx --contract-hash yyyyy -f 1111111

**Expected behavior**
To not throw an exception and successfully recover the coins

**Screenshots**
```
sit wallet recover_pool_nft --launcher-hash xxxxx --contract-hash yyyyy -f 1111111
found 3 expired coins, total amount: 375000000000
Traceback (most recent call last):
  File "/farming/silicoin-blockchain/venv/bin/sit", line 33, in <module>
    sys.exit(load_entry_point('chia-blockchain', 'console_scripts', 'sit')())
  File "/farming/silicoin-blockchain/chia/cmds/chia.py", line 133, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/farming/silicoin-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/farming/silicoin-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/farming/silicoin-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/farming/silicoin-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/farming/silicoin-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/farming/silicoin-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/farming/silicoin-blockchain/chia/cmds/wallet.py", line 269, in recover_pool_nft
    asyncio.run(do_recover_pool_nft(contract_puzzle_hash, launcher_hash, fingerprint))
  File "/farming/silicoin-blockchain/venv/lib/python3.8/site-packages/nest_asyncio.py", line 32, in run
    return loop.run_until_complete(future)
  File "/farming/silicoin-blockchain/venv/lib/python3.8/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/farming/silicoin-blockchain/chia/cmds/wallet.py", line 244, in do_recover_pool_nft
    tx = await wallet_client_f.recover_pool_nft(launcher_hash, contract_hash, coins)
AttributeError: 'tuple' object has no attribute 'recover_pool_nft'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f1e259fa1f0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f1e259fa3d0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f1e257422e0>, 4950.703812709)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f1e259fa1c0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f1e25742640>, 4950.711776921)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f1e259fa490>

```

- OS: Ubuntu
- OS Version/Flavor: 20.04LTS
- CPU: Xeon 6248R

**Comment by XCHSystems** [comment]
Looks like DEV Teams are not very pro-active at looking at the bugs
