### ISSUE TITLE
Hi I need some help, I tried to install the 0.05 but there was a error[BUG]

### ISSUE THREAD

**Issue by evobenny** [silicoin-network/silicoin-blockchain#29]
I was farming on 0.04 fine and closed of 0.04 to upgrade to 0.05 but when i tried to install 0.05 there was an error saying 

![image](https://user-images.githubusercontent.com/87024916/124615478-e5214680-dea7-11eb-834b-4e347184baf7.png)

then when I click on the open set up log it gave me this :

which was weird as it is 6th July 2021. I have rebooted the PC and have admin rights, remove silicoin and delete the .silicon folder from the user files, and deleted the silicon block chain from the appdata files but still unable to install this 0.05. I tried installing 0.04 bu t the same issue happen.

right now there is no .silicoin folder in the user file thus there is no mainnet and no log.

I am running windows 10 , amd 5600x, 32gb ram.

2021-02-03 20:16:38> Program: Starting Squirrel Updater: --install .
2021-02-03 20:16:38> Program: Starting install, writing to C:\Users\evobe\AppData\Local\SquirrelTemp
2021-02-03 20:16:38> Program: About to install to: C:\Users\evobe\AppData\Local\WhatsApp
2021-02-03 20:16:38> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\evobe\AppData\Local\WhatsApp\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2021-02-03 20:16:38> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\evobe\AppData\Local\WhatsApp\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2021-02-03 20:16:38> CheckForUpdateImpl: Reading RELEASES file from C:\Users\evobe\AppData\Local\SquirrelTemp
2021-02-03 20:16:38> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2021-02-03 20:16:39> ApplyReleasesImpl: Writing files to app directory: C:\Users\evobe\AppData\Local\WhatsApp\app-2.2102.8
2021-02-03 20:16:41> LogHost: Rigging execution stub for WhatsApp_ExecutionStub.exe to C:\Users\evobe\AppData\Local\WhatsApp\WhatsApp.exe
2021-02-03 20:16:42> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\evobe\AppData\Local\WhatsApp\app-2.2102.8\WhatsApp.exe]
2021-02-03 20:16:43> ApplyReleasesImpl: Starting fixPinnedExecutables
2021-02-03 20:16:43> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2021-02-03 20:16:43> ApplyReleasesImpl: Fixing up tray icons
2021-02-03 20:16:43> ApplyReleasesImpl: cleanDeadVersions: for version 2.2102.8
2021-02-03 20:16:43> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2.2102.8
21976> 2021-03-12 22:26:09> Program: Starting Squirrel Updater: --install .
21976> 2021-03-12 22:26:09> Program: Starting install, writing to C:\Users\evobe\AppData\Local\SquirrelTemp
21976> 2021-03-12 22:26:09> Program: About to install to: C:\Users\evobe\AppData\Local\Discord
21976> 2021-03-12 22:26:09> SingleGlobalInstance: Grabbing lockfile with timeout of 00:00:10
21976> 2021-03-12 22:26:09> CheckForUpdateImpl: Reading RELEASES file from C:\Users\evobe\AppData\Local\SquirrelTemp
21976> 2021-03-12 22:26:09> CheckForUpdateImpl: Remote version 0.0.309 differs from local 
21976> 2021-03-12 22:26:09> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
21976> 2021-03-12 22:26:09> ApplyReleasesImpl: Writing files to app directory: C:\Users\evobe\AppData\Local\Discord\app-0.0.309
21976> 2021-03-12 22:26:11> ApplyReleasesImpl: Moving file C:\Users\evobe\AppData\Local\Discord\app-0.0.309\lib\net45\app.ico to C:\Users\evobe\AppData\Local\Discord\app-0.0.309\app.ico
21976> 2021-03-12 22:26:11> ApplyReleasesImpl: Moving file C:\Users\evobe\AppData\Local\Discord\app-0.0.309\lib\net45\chrome_100_percent.pak to C:\Users\evobe\AppData\Local\Discord\app-0.0.309\chrome_100_percent.pak
21976> 2021-03-12 22:26:11> ApplyReleasesImpl: Moving file C:\Users\evobe\AppData\Local\Discord\app-0.0.309\lib\net45\d3dcompiler_47.dll to C:\Users\evobe\AppData\Local\Discord\app-0.0.309\d3dcompiler_47.dll
21976> 2021-03-12 22:26:11> ApplyReleasesImpl: Moving file C:\Users\evobe\AppData\Local\Discord\app-0.0.309\lib\net45\chrome_200_percent.pak to C:\Users\evobe\AppData\Local\Discord\app-0.0.309\chrome_200_percent.pak
21976> 2021-03-12 22:26:11> ApplyReleasesImpl: Moving file C:\Users\evobe\AppData\Local\Discord\app-0.0.309\lib\net45\Discord.exe to C:\Users\evobe\AppData\Local\Discord\app-0.0.309\Discord.exe
21976> 2021-03-12 22:26:11> ApplyReleasesImpl: Moving file C:\Users\evobe\AppData\Local\Discord\app-0.0.309\lib\net45\ffmpeg.dll to C:\Users\evobe\AppData\Local\Discord\app-0.0.309\ffmpeg.dll
21976> 2021-03-12 22:26:11> ApplyReleasesImpl: Moving file C:\Users\evobe\AppData\Local\Discord\app-0.0.309\lib\net45\icudtl.dat to C:\Users\evobe\AppData\Local\Discord\app-0.0.309\icudtl.dat
21976> 2021-03-12 22:26:11> ApplyReleasesImpl: Moving file C:\Users\evobe\AppData\Local\Discord\app-0.0.309\lib\net45\libEGL.dll to C:\Users\evobe\AppData\Local\Discord\app-0.0.309\libEGL.dll
21976> 2021-03-12 22:26:11> ApplyReleasesImpl: Moving file C:\Users\evobe\AppData\Local\Discord\app-0.0.309\lib\net45\libGLESv2.dll to C:\Users\evobe\AppData\Local\Discord\app-0.0.309\libGLESv2.dll
21976> 2021-03-12 22:26:11> ApplyReleasesImpl: Moving file C:\Users\evobe\AppData\Local\Discord\app-0.0.309\lib\net45\snapshot_blob.bin to C:\Users\evobe\AppData\Local\Discord\app-0.0.309\snapshot_blob.bin
21976> 2021-03-12 22:26:11> ApplyReleasesImpl: Moving file C:\Users\evobe\AppData\Local\Discord\app-0.0.309\lib\net45\resources.pak to C:\Users\evobe\AppData\Local\Discord\app-0.0.309\resources.pak
21976> 2021-03-12 22:26:11> ApplyReleasesImpl: Moving file C:\Users\evobe\AppData\Local\Discord\app-0.0.309\lib\net45\Squirrel.exe to C:\Users\evobe\AppData\Local\Discord\app-0.0.309\Squirrel.exe
21976> 2021-03-12 22:26:11> ApplyReleasesImpl: Moving file C:\Users\evobe\AppData\Local\Discord\app-0.0.309\lib\net45\v8_context_snapshot.bin to C:\Users\evobe\AppData\Local\Discord\app-0.0.309\v8_context_snapshot.bin
21976> 2021-03-12 22:26:11> ApplyReleasesImpl: Moving file C:\Users\evobe\AppData\Local\Discord\app-0.0.309\lib\net45\vulkan-1.dll to C:\Users\evobe\AppData\Local\Discord\app-0.0.309\vulkan-1.dll
21976> 2021-03-12 22:26:11> ApplyReleasesImpl: Moving file C:\Users\evobe\AppData\Local\Discord\app-0.0.309\lib\net45\vk_swiftshader.dll to C:\Users\evobe\AppData\Local\Discord\app-0.0.309\vk_swiftshader.dll
21976> 2021-03-12 22:26:12> ApplyReleasesImpl: Started updateSelf pid 20272
21976> 2021-03-12 22:26:12> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\evobe\AppData\Local\Discord\app-0.0.309\Discord.exe]
21976> 2021-03-12 22:26:12> Utility: Process Started: C:\Users\evobe\AppData\Local\Discord\app-0.0.309\Discord.exe --squirrel-install 0.0.309, pid 16736
21976> 2021-03-12 22:26:13> Utility: Received exitcode 0 from process C:\Users\evobe\AppData\Local\Discord\app-0.0.309\Discord.exe
21976> 2021-03-12 22:26:14> ApplyReleasesImpl: ran C:\Users\evobe\AppData\Local\Discord\app-0.0.309\Discord.exe, pid 15012
21976> 2021-03-12 22:26:14> ApplyReleasesImpl: Starting fixPinnedExecutables
21976> 2021-03-12 22:26:14> ApplyReleasesImpl: fixPinnedExecutables: newCurrentFolder: app-0.0.309
21976> 2021-03-12 22:26:14> ApplyReleasesImpl: File 'C:\Users\evobe\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\Narrator.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
21976> 2021-03-12 22:26:14> ApplyReleasesImpl: File 'C:\Users\evobe\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\On-Screen Keyboard.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
21976> 2021-03-12 22:26:14> ApplyReleasesImpl: Updating shortcut C:\Users\evobe\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Discord Inc\Discord.lnk
21976> 2021-03-12 22:26:14> ApplyReleasesImpl: Updating shortcut C:\Users\evobe\Desktop\Discord.lnk
21976> 2021-03-12 22:26:14> ApplyReleasesImpl: Fixing up tray icons
21976> 2021-03-12 22:26:14> ApplyReleasesImpl: cleanDeadVersions: for version 0.0.309
21976> 2021-03-12 22:26:14> ApplyReleasesImpl: cleanDeadVersions: exclude current version folder app-0.0.309

**Comment by evobenny** [comment]
ok new update, I manage to find the silicoin blockchain, under the appdata. 

C:\Users\evobe\AppData\Local\Silicoin-blockchain\app-0.0.5 when I went in and double click the silicoin.exe and it launched! 

It seem like this is the only way for it to launch for me.
